# This script is provided by github.com/bool64/dev.
name: coverage
on:
  push:
    branches:
      - master
      - main
  pull_request:

# Cancel the workflow in progress in newer build is about to start.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  GO111MODULE: "on"
  RUN_BASE_COVERAGE: "on"  # Runs test for PR base in case base test coverage is missing.
  TARGET_DELTA_COV: 90     # Target coverage of changed lines, in percents
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.18.x ]
    name: "Golang Test Coverage"
    runs-on: ubuntu-latest
    steps:
      - name: Install Go stable
        if: matrix.go-version != 'tip'
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Go tip
        if: matrix.go-version == 'tip'
        run: |
          curl -sL https://storage.googleapis.com/go-build-snap/go/linux-amd64/$(git ls-remote https://github.com/golang/go.git HEAD | awk '{print $1;}').tar.gz -o gotip.tar.gz
          ls -lah gotip.tar.gz
          mkdir -p ~/sdk/gotip
          tar -C ~/sdk/gotip -xzf gotip.tar.gz
          ~/sdk/gotip/bin/go version
          echo "PATH=$HOME/go/bin:$HOME/sdk/gotip/bin/:$PATH" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Go cache
        uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-cache

      - name: Generate Golang source hash base
        id: hash-base
        run: echo "::set-output name=value::${{ hashFiles('**/*.go','!vendor/**') }}"
      - name: Cache base cover profile
        id: cache-base
        uses: actions/cache@v3
        with:
          path: cover-${{ steps.hash-base.outputs.value }}.profile
          key: cover-profile-${{ steps.hash-base.outputs.value }}
      - name: Run test for base code
        if: env.RUN_BASE_COVERAGE == 'on' && steps.base-coverage.outputs.cache-hit != 'true' && github.event.pull_request.base.sha != ''
        run: |
          git fetch origin main ${{ github.event.pull_request.base.sha }}
          HEAD=$(git rev-parse HEAD)
          git reset --hard ${{ github.event.pull_request.base.sha }}
          (go test -cover -coverprofile=unit.coverprofile && go tool cover -func=./unit.coverprofile > unit-base.txt) || echo "Failed to run tests in base"
          git reset --hard $HEAD
      - name: Restore base test coverage
        id: base-coverage
        if: github.event.pull_request.base.sha != ''
        uses: actions/cache@v2
        with:
          path: |
            unit-base.txt
          # Use base sha for PR or new commit hash for master/main push in test result key.
          key: ${{ runner.os }}-unit-test-coverage-${{ (github.event.pull_request.base.sha != github.event.after) && github.event.pull_request.base.sha || github.event.after }}
      - name: Test
        id: test
        run: |
          (go test -cover -coverprofile=unit.coverprofile && go tool cover -func=./unit.coverprofile > unit.txt) || echo "Failed to run tests in head"
          TOTAL=$(grep 'total:' unit.txt)
          echo "${TOTAL}"
          echo "::set-output name=total::$TOTAL"
      - name: Fetch gocovdiff @master SHA-1
        id: gocovdiff-main
        run: |
          sha1=$(curl \
            --header "Accept: application/vnd.github.v3+json" \
            --silent \
              https://api.github.com/repos/vearutop/gocovdiff/branches/master | \
                jq --raw-output ".commit.sha")
          echo "::set-output name=sha1::$sha1"
      - name: Cache gocovdiff
        id: cache-gocovdiff
        uses: actions/cache@v3
        with:
          path: ~/go/bin/gocovdiff
          key: ${{ runner.os }}-gocovdiff-sha1-${{ steps.gocovdiff-main.outputs.sha1 }}
      - name: Install gocovdiff
        if: steps.cache-gocovdiff.outputs.cache-hit != 'true'
        run: go install github.com/vearutop/gocovdiff@master
      - name: Annotate missing test coverage
        id: annotate
        if: github.event.pull_request.base.sha != ''
        run: |
          git fetch origin main ${{ github.event.pull_request.base.sha }}
          REP=$(gocovdiff -cov unit.coverprofile -gha-annotations gha-unit.txt -exclude _testdata -target-delta-cov ${TARGET_DELTA_COV})
          echo "${REP}"
          REP="${REP//$'\n'/%0A}"
          cat gha-unit.txt
          DIFF=$(test -e unit-base.txt && gocovdiff -func-cov unit.txt -func-base-cov unit-base.txt || echo "Missing base coverage file")
          DIFF="${DIFF//$'\n'/%0A}"
          echo "::set-output name=rep::$REP"
          echo "::set-output name=diff::$DIFF"

      - name: Comment Test Coverage
        continue-on-error: true
        if: github.event.pull_request.base.sha != ''
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: unit-test
          message: |
            ### Unit Test Coverage
            ${{ steps.test.outputs.total }}
            ${{ steps.annotate.outputs.total }}
            <details><summary>Coverage of changed lines</summary>
            
            ${{ steps.annotate.outputs.rep }}

            </details>

            <details><summary>Coverage diff with base branch</summary>

            ${{ steps.annotate.outputs.diff }}
            
            </details>

      - name: Store base coverage
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        run: cp unit.txt unit-base.txt

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./unit.coverprofile
          flags: unittests
